### ISSUE TITLE
coffee-script.register() has no support for sourcemaps

### ISSUE THREAD

**Issue by gaurav21r** [jashkenas/coffeescript#4214]
I have tests written in js (mocha) where I am directly `require`ing `.coffee` files. And using [`node-inspector`](https://github.com/node-inspector/node-inspector) to debug.

Using `require('coffee-script').register()` I am not able to generate sourcemaps.

I found a solution [here](https://gist.github.com/yamadapc/ffafc2c2758a9bef9de4) but I don't think it works. Although I just did a bit of surface level digging over the annotated source and seems that sourcemaps are getting generated when using the `coffee` compiler. Could it be an easy fix just to "turn on" sourcemaps for `register()` as well?

Without sourcemaps debugging nodejs scripts in coffee are nothing short of a nightmare :(

**Comment by lydell** [comment]
I think this is fixed by #4111.

**Comment by gaurav21r** [comment]
I don't know @lydell While the PR does say it attempts to fix this issue, I'm still getting no sourcemaps with mocha and node-inspector. Let me see if I can reproduce my case here somehow.

**Comment by lydell** [comment]
Note: That PR has not been released, so you'd have to `npm install jaskenas/coffeescript` to try it out.

**Comment by gaurav21r** [comment]
@lydell THanks!!! Will try it out. Any specific reason this hasn't been released? Or would it be a part of the next general release?

**Comment by lydell** [comment]
Yes, it would be part of the next release. There’s no specific reason it hasn’t been released. Nobody has simply felt like doing it. See also: https://github.com/jashkenas/coffeescript/wiki/%5BHowto%5D-Hacking-on-the-CoffeeScript-Compiler#11-preparing-a-new-release

**Comment by gaurav21r** [comment]
@lydell Thanks for the update :+1: 

I `npm`ed the GitHub repo from `master` and ran `mocha` with `node-debug`. Its definitely looking for Source Maps now, but its not getting generated. PFA Screenshot. Also, is there an option in `require('coffee-script').register()` to enable inline-sourcemaps?

**Comment by lydell** [comment]
- `require('coffee-script').register()` does not accept any options.
- `require('coffee-script').register()` is supposed to add `//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKI...` at the end of everything it compiles.
- It’s really odd that Chrome went looking for a `.map` file for you. Could you post the end of the contents of your `.coffee` file so we can see if it specifies `//# sourceMappingUrl=.../createTablesForWrite.coffee.map` or something?

Here’s a small test I did:

```
$ mkdir coffee-test
$ cd coffee-test
$ npm install jashkenas/coffeescript
$ cp node_modules/coffee-script/lib/coffee-script/register.js .
$ vim node_modules/coffee-script/lib/coffee-script/register.js
$ git diff --no-index register.js node_modules/coffee-script/lib/coffee-script/register.js
diff --git a/register.js b/node_modules/coffee-script/lib/coffee-script/register.js
index 93cc6e7..9d18aa9 100644
--- a/register.js
+++ b/node_modules/coffee-script/lib/coffee-script/register.js
@@ -13,6 +13,7 @@
   loadFile = function(module, filename) {
     var answer;
     answer = CoffeeScript._compileFile(filename, false, true);
+    console.log('loadFile', filename, answer);
     return module._compile(answer, filename);
   };
$ echo 'require("coffee-script").register(); require("./test")' > entry.js
$ echo 'console.log "it works!"' > test.coffee
$ node entry
loadFile /home/lydell/coffee-test/test.coffee (function() {
  console.log("it's working!");

}).call(this);

//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAiZmlsZSI6ICIiLAogICJzb3VyY2VSb290IjogIiIsCiAgInNvdXJjZXMiOiBbCiAgICAiIgogIF0sCiAgIm5hbWVzIjogW10sCiAgIm1hcHBpbmdzIjogIkFBQUE7RUFBQSxPQUFPLENBQUMsR0FBUixDQUFZLGVBQVo7QUFBQSIKfQ==
//# sourceURL=/home/lydell/coffee-test/test.coffee
it works!
```

That shows that `require('coffee-script').register()` seems to be outputting an inline source map as expected. However, this is what the source map looks like when decoded (copy everything after `base64,` and paste it inside `atob('')` and run it in the console to decode):

```json
{
  "version": 3,
  "file": "",
  "sourceRoot": "",
  "sources": [
    ""
  ],
  "names": [],
  "mappings": "AAAA;EAAA,OAAO,CAAC,GAAR,CAAY,eAAZ;AAAA"
}
```

It’s a bit odd that 'sources' only contain an empty string. Otherwise it looks pretty good, I think. Compare with `coffee -cm test.coffee && cat test.js.map`: 

```json
{
  "version": 3,
  "file": "test.js",
  "sourceRoot": "",
  "sources": [
    "test.coffee"
  ],
  "names": [],
  "mappings": ";AAAA;EAAA,OAAO,CAAC,GAAR,CAAY,WAAZ;AAAA"
}
```

**Comment by lydell** [comment]
I made a pull request (#4223) for fixing the strange things I found in this issue, but I don’t know if it will make any difference for you.

**Comment by gaurav21r** [comment]
@lydell OMG :100: :star: Thank you so much for all this support :exclamation: Let me just try this and get back to you :)

**Comment by gaurav21r** [comment]
Yep Working. Thank you so much @lydell :smiley: :100:
