### ISSUE TITLE
node v7.1 reports deprecation warning

### ISSUE THREAD

**Issue by metalim** [jashkenas/coffeescript#4358]
Running CoffeeScript command-line REPL with latest node (7.1.0) reports following on each command execution:
```
└> coffee
coffee> (node:29643) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

```

**Comment by GeoffreyBooth** [comment]
Fixed in #4340, will go out with the next release. You can preview it now by cloning this repo and running `bin/coffee`.

**Comment by Qix-** [comment]
I'm still getting this:

<img width="617" alt="screen shot 2017-04-13 at 8 04 47 pm" src="https://cloud.githubusercontent.com/assets/885648/25031848/892af280-2084-11e7-98f7-b79cd4a867d3.png">

```console
$ node --version
v7.9.0
```
